name: Publish package on NuGet

on:
  push:
    branches: [ develop ]

jobs:
  job_1: 
    name: Xalendar build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'src/'
      
    - name: Build
      run: dotnet build Xalendar --configuration Release --no-restore
      working-directory: 'src/'
      
  job_2: 
    name: Xalendar test
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        dotnet-version: '5.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'src/'
      
    - name: Run unit tests for Xalendar.Tests
      run: dotnet test src/Xalendar.Tests/Xalendar.Tests.csproj -v n /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      
    - name: Send report to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
  job_3: 
    name: Xalendar pre-release publish
    needs: job_2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'src/'
      
    - name: Build
      run: dotnet build Xalendar --configuration Release --no-restore
      working-directory: 'src/'
      
    - name: Pack
      run: dotnet pack -v normal --configuration Release --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID src/*/Xalendar.csproj
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./src/Xalendar/bin/Release/*.nupkg
      
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Xalendar/Xalendar.csproj
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
